# Generated by Django 3.2.7 on 2021-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
